In [1]:

# vector,Matrices

In [2]:
import numpy as np
simple=[1,2,3]

In [3]:
np.array(simple)

array([1, 2, 3])

In [4]:
simple1=([1,2],[4,6],[5,10])
np.array(simple1)

array([[ 1,  2],
       [ 4,  6],
       [ 5, 10]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones(2).shape

(2,)

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [11]:
b=np.random.randn(20)
b

array([-0.93741518,  2.01959904, -1.0639341 , -0.12754268, -0.67291441,
       -0.06856884,  1.74967697,  1.27125245,  0.46314027,  0.15250011,
        1.65517978,  1.66232111, -0.25459591, -1.13548009,  1.12242898,
       -0.30266638, -1.82822963,  1.62617534,  0.08736637, -0.10561985])

In [12]:
np.random.randint(10)

5

In [13]:
b.reshape(5,4)

array([[-0.93741518,  2.01959904, -1.0639341 , -0.12754268],
       [-0.67291441, -0.06856884,  1.74967697,  1.27125245],
       [ 0.46314027,  0.15250011,  1.65517978,  1.66232111],
       [-0.25459591, -1.13548009,  1.12242898, -0.30266638],
       [-1.82822963,  1.62617534,  0.08736637, -0.10561985]])

In [14]:
b.dtype

dtype('float64')

In [15]:
np.array([b.min(),b.max(),b.argmin(),b.argmax(),b.mean()])

array([-1.82822963,  2.01959904, 16.        ,  1.        ,  0.26563367])

In [16]:
b.T

array([-0.93741518,  2.01959904, -1.0639341 , -0.12754268, -0.67291441,
       -0.06856884,  1.74967697,  1.27125245,  0.46314027,  0.15250011,
        1.65517978,  1.66232111, -0.25459591, -1.13548009,  1.12242898,
       -0.30266638, -1.82822963,  1.62617534,  0.08736637, -0.10561985])

In [17]:
a=np.arange(21)

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
a[0:2]

array([0, 1])

In [20]:
a[2:5]=101  #broadcasting...one value replace the provided range
a[2:5]

array([101, 101, 101])

In [21]:
a  # change the original array

array([  0,   1, 101, 101, 101,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [22]:
c=([1,2],[2,3],[3,5])
mtx=np.array(c)
mtx

array([[1, 2],
       [2, 3],
       [3, 5]])

In [23]:
mtx[1][0]

2

In [24]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b=a[a>5]

In [26]:
a+5
b

array([6, 7, 8, 9])

In [27]:
a=np.arange(10).reshape(2,5)
print(a)
print('\n')
print(a.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]


[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
